---
- name: 'Configure WIFI'
  copy: src=./wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

- name: 'Run rpi-update'
  command: rpi-update

- name: 'Update APT package cache'
  action: apt update_cache=yes cache_valid_time=3600
  become: True

- name: 'Upgrade APT to the lastest packages'
  action: apt upgrade=full
  become: True

- name: 'Install misc packages'
  apt: name={{ item }} state=present
  become: True
  with_items:
    - vim-gtk
    - vim-gtk
    - autocutsel

- name: restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for Raspberry to come back
  local_action: wait_for host={{ inventory_hostname }}
                state=started
  sudo: false
